## Introduction

Welcome to RMCV 101! In this submodule, we will talk about basic Python concepts, tools, and methodology so that you can start working right away.

We will be using **Python 3** and Jupyter Notebook throughout the entire submodule.

### Prerequisites

- Have installed Python 3 and Jupyter Notebook. If you haven't, visit INSTALL.md
- Some programming background

Ready? Let's get started! Before we start, you need to switch to the Jupyter Notebook on your local machine rather than viewing it on the GitHub. Otherwise you will not be able to write code.

### ... but how do I use Jupyter Notebook?

In the last "verification" step back in the INSTALL.md, you ran

```
jupyter notebook
```

in some folder and there is a browser window popping up? That's how you are going to use the jupyter notebook. Pull up a new terminal session. Navigate to wherever this file is located in the terminal with command lines. Then run the magical 'jupyter notebook' command. After doing so you should see a browser window that looks like this

<img src="./imgs/00_jupyter_navigation.jpg" alt="drawing" width="200"/>

Feel free to click any NoI (Notebook of Interest :D). Here we will choose `00_basic_operations.ipynb`. Now you should be seeing the content in the notebook on your browser.

Unlike IDE/Editor, things in Jupyter Notebook are typically organized in **cells**. There are different types of cells. For most of the time, we play with **code** cells. Another frequently used type of cells is the **Markdown** cell. Let's talk about code cells first.

Click on any code cell to highlight that particular cell. If you've followed the instruction and are running the Jupyter Notebook on your own machine, you should be able to edit the highlighted cell.

To run the code segment in any highlighted cell, hit the "Run" button in the toolbar (or press `shift+return` on your keyboard). What's changed after hitting "Run"?

Note that output from your code will be printed **below** the corresponding code cell.

Now let's talk about Python.

### print statement

Python has a print statement that works like C and many many other languages.

In [1]:
print("Hello World!")

Hello World!


### Exercise

Write a line of code that prints out "Illini RM is awesome!"

In [2]:
# Your code here

### Data Types

Now let's move on to data types. Unlike many languages, the highly dynamic nature of Python allows Python programmers to avoid the repetitive work of declaring data type (to bo precise, Python follows the philosophy of so-called Duck Typing).

In [3]:
a = 1     # a is an integer
print(a)  # print statement in Python is highly dynamic as well...

1


In [4]:
a = 1 << 31 # This almost gets to the upper bound of uint32_t!
print(a)

2147483648


In [5]:
a = 1 << 1221 # Will Python be able to handle this?
print(a)

36109768628918289680181237270032176609660606339767210966742701055988446142119009309210673492233648704399859345589716307754006457437790742301883204648784295036787367024590304587829068214346826643210695217080553232099119066551661246199664630858594053699110560125659505447329235914525667766141695080483044195420836646609268481232160720065016972047104891716446477617201152


In [6]:
a = 1.0
print(a)

1.0


In [7]:
a = "I'm a string!"
print(a)

I'm a string!


In [8]:
# List
a = [1, 2, "list can hold different type of data", 1.2]
print(a)
print(type(a[0])) # index starts from 0
print(type(a[2]))
print(type(a[3]))

[1, 2, 'list can hold different type of data', 1.2]
<class 'int'>
<class 'str'>
<class 'float'>


In [9]:
a = (1, "hey") # Tuples
print(a)

(1, 'hey')


In [10]:
a = [(1, 2), [2, 3, [5]]] # Nested list/tuple
print(a)

[(1, 2), [2, 3, [5]]]


**Dictionary** is probably the essence of Python programming that it worths a Markdown cell for introducing it :D

The backend of **Dictionary** is a *hashtable*. As you have learnt (or will have learnt) from CS225, access to/from hashtable is $O(1)$, which is a very desriable property when there is a large amount of key/value pairs.

In [11]:
a = {"hey": "you!", "I'm": "a", "dictionary!": 42, 1221: 42}
print(a.keys())
print(a.values())
print(a["hey"])
print(a[1221])

dict_keys(['hey', "I'm", 'dictionary!', 1221])
dict_values(['you!', 'a', 42, 42])
you!
42


### String Formatting

String formatting in Python is intuitive.

In [12]:
s = "{0} is {1}! {0} has {2} robots!"
print(s.format("Illini RM", "awesome", 10))

Illini RM is awesome! Illini RM has 10 robots!


In [13]:
my_tuple = ("Illini RM", "awesome", 5) # List formatting in Python
print(s.format(*my_tuple))

Illini RM is awesome! Illini RM has 5 robots!


In [14]:
s = "{1} is {0}! {1} has {2} robots!" # the order of indices can be changed as well
print(s.format("awesome", "Illini RM", 10))

Illini RM is awesome! Illini RM has 10 robots!


### Exercise

Make a tuple such that the following code prints out:
Bob is smart! Bob has RoboMaster S1 robots!

In [ ]:
my_tuple = () # Fill in my_tuple
print(s.format(*my_tuple)) # This automatically takes all elements in my_tuple as parameters

### if/for
The `if` control flow is very straight forward. 

In [15]:
if (True): print("The condition is true")
if(not True): print("Never got printed")

if (10000 >= 1 and (1 in {1,2,3})): print("One thousand is greater than one and 1 is an element of {1,2,3}.")

if("R" in "Rob" in "Robomaster" in "IlliniRobomaster"):print("R in Rob in Robomaster in IlliniRobomaster")
    
# It is worth noticing that scripting languages like python may not error until code is executed.
if (False):
    bug = 1000 / 0

temperature = 41  #CHANGE ME

if (temperature > 50): print("50+")
elif (40 < temperature <= 50): print("40~50")
else: print("40-")

The condition is true
One thousand is greater than one and 1 is an element of {1,2,3}.
R in Rob in Robomaster in IlliniRobomaster
40~50


The `for` control flow have many usages.

In [16]:
# When used with range() it is a traditional for loop
output=[]
for i in range(-2,11):#This goes from -2 to 10
   output+=[i]
print(output)

# It allows easy transverse of any lists-like data structures
some_list=["a","b",1,True,["another","list"]]
for item in some_list: print(str(item))

# Use `continue` to skip to next loop and `break` to break out the loop;
output=[]
for i in range(1,10):
    if(i%2==0):continue
    if(i==5):break
    output+=[i]
print(output)

# `for` can also be used to construct lists in a one-liner

sugar = [x**2 for x in [1,2,3,4,5]]
print(sugar)

[-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a
b
1
True
['another', 'list']
[1, 3]
[1, 4, 9, 16, 25]


### Exercise
Write some code to print out all food items in the list. 

In [17]:
my_set=[1,"cheese stake(food)", "cheese steak(food)", True, "Alma Mater(food?)", "Pop Tarts(food!)","foodn't"]

### function
A function in python is what you would expect in most languages. 

In [18]:
def callme(x):
    y = 100

    # Define functions anywhere and use them by their name
    def helper1(x):
        # y is invisible here
        return x + 1

    # Define lambda functions if you wish to use variables inside current scope
    y = 100

    def poooowwer(z):
        return z**y

    return poooowwer(helper1(x))


print(callme(2))

# We usually pass lambda functions around for all sorts of purposes


def lambda_applier(list_to_apply_lambda, lambda_to_apply):
    ret = []
    for i in list_to_apply_lambda:
        ret += [lambda_to_apply(i)]
    return ret


print(lambda_applier([1, 2, 3], lambda x: x << x))


# Recursion works as usual
def generate_series(x, y):
    if (x > 999):
        return
    print(x)
    generate_series(y, x + y)


generate_series(1, 1)

515377520732011331036461129765621272702107522001
[2, 8, 24]
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


### Exercise
Package a few previous excercises into functions and make them accept variable parameters. 

### Class
Classes are a way of packaging functions and data into one data structure for easier abstraction

In [19]:
# Copied from https://www.w3schools.com/python/python_classes.asp
class Person:
    # We can hold default member values here
    name = "Unnamed"
    age = -1

    # the __init__ constructor is called whenever a Person class is created
    def __init__(self, name, age):
        print(str(name) + " of age " + str(age) + " is born...")
        self.name = name
        self.age = age

    def grow(self):
        print(str(self.name) + " just got more life experience")
        self.age += 1


p1 = Person("John", 998)
p1.grow()
print(p1.name)
print(p1.age)


#-----------------------------------------------------------
# The Journalist class inherits Person, having everything from Person class plus its on data members & methods.
class Journalist(Person):
    def grow(self):
        print(str(self.name) + " just got more life experience and -1s")
        self.age -= 1

    def run(self):
        print(self.name + "is running very fast!")


p1 = Journalist("Peter", 60)
p1.grow()
p1.run()
print(p1.age)

John of age 998 is born...
John just got more life experience
John
999
Peter of age 60 is born...
Peter just got more life experience and -1s
Peteris running very fast!
59


### Exercise
Write classes of Person, Rock, Paper, Scissor, HandGrenade, and a function accpeting two classes and print out the winner. 

In [ ]:
# Write your code here

### Imports
The keyword imports allows you to use external libiaries.

NumPy is a Python library that is used in many, many, and many places. If you apply for a job that requires
Python proficiency, you probably want to tell them you are proficient in Python. It's also a library
that we often used in Robotics. We will use NumPy as an example here and will go in-depth in the next section.

In [ ]:
# This will install a commonly used multi-dimensional data operation libriary for you
!pip3 install numpy -U

In [20]:
import numpy as np
from numpy import random

arr = np.zeros([19, 23, 31]) 
arr += random.rand(*[19, 23, 31]) # This way we can use functions otherwise unavail to us

print(arr)

# We will probably cover more usage of various libiaries later

[[[0.5917733  0.26483232 0.22319002 ... 0.15359688 0.79877117 0.10093683]
  [0.61922413 0.33395184 0.89739604 ... 0.33218755 0.03730845 0.56378666]
  [0.55091185 0.17897728 0.47317831 ... 0.87429092 0.25719995 0.90529553]
  ...
  [0.23395162 0.72624719 0.79837007 ... 0.29419035 0.0320014  0.60511432]
  [0.36658616 0.36238907 0.42526047 ... 0.11118535 0.6866005  0.12728272]
  [0.73808673 0.74173268 0.76367836 ... 0.86521171 0.88536213 0.11994832]]

 [[0.70948564 0.98550591 0.0106099  ... 0.2108994  0.08267362 0.69733586]
  [0.79194467 0.1955801  0.3424576  ... 0.40595095 0.98159519 0.87676878]
  [0.62810227 0.52059335 0.90368544 ... 0.4148104  0.82198486 0.29216477]
  ...
  [0.26195137 0.55451375 0.13133525 ... 0.47758371 0.70599293 0.92744317]
  [0.59444495 0.53808881 0.1335833  ... 0.81947575 0.17930111 0.95869878]
  [0.32228377 0.71223617 0.552702   ... 0.65512542 0.4615767  0.63755641]]

 [[0.74105493 0.87593137 0.17270647 ... 0.59786121 0.47343534 0.34729517]
  [0.46958628 0.902110

### MP0.1

Implement factorial
$$k! = k \cdot (k - 1) \cdot \cdots \cdot 2 \cdot 1 \quad \text{for } k \in \mathbb{Z}_{>0}$$
as recursive and iterative functions.

In [ ]:
# Your code here for MP0.1

### MP0.2

Implement a function `corn_plz` such that it returns `True` when you have **more corns** than other things in the input.
Note that the input is provided by some shitty code and is in one string for some reason.

Example input and expected output:
```
my_input = "corn55rice2chicken33beef2sushi5"
corn_plz(my_input) # return True

my_input = "rice5435corn111water56438frenchfries1231orange543245235423532mango1221"
corn_plz(my_input) # return False
```

In [ ]:
# Your code here for MP0.2

### MP0.3

This is a reading assignment. You don't have to write any code for this.

http://sthurlow.com/python/lesson06/

## Finally...

After finishing this iPython notebook, you should be able to know a little about the interpretive nature (doesn't require compilation) of Python and basic operations in Python. However, there's still much to be learned (for example, list comprehensions/syntactic sugar and so on...). Feel free to ask someone who is familiar with Python!